### ISSUE TITLE
Rendering mesh to mesh animation

### ISSUE THREAD

**Issue by ggxxii** [waczjoan/gaussian-mesh-splatting#12]
Hi, thank you for making this amazing work open-source.
For the animation part, you mentioned it's possible to render animation from mesh to mesh, I'm a bit confused, does this mean we need an obj sequence?

**Comment by ggxxii** [comment]
So if I understand correctly, it's more like a mesh interpolation? And the transformation is linear?

**Comment by waczjoan** [comment]
in this case, for simplicity -- yes :)
