### ISSUE TITLE
Is GaussianMeshModel optimize initial input mesh?

### ISSUE THREAD

**Issue by ggxxii** [waczjoan/gaussian-mesh-splatting#13]
Hi,

I've been diving into your code on the model and noticed the vertices of the input model are sent to parameters but not used in the density and prune process. So I'm wondering for ordinary mesh, will GaMeS optimize both input mesh and assigned gaussian points?

**Comment by Mike001-wq** [comment]
I wonder, too

**Comment by waczjoan** [comment]
There is an option that our model optimize initial mesh. It was used when initial mesh is not perfect. In that case model can change vertices positions, and of course Gaussians positions, but it won't change number of faces, or neither number of Gaussians.

**Comment by Mike001-wq** [comment]
> There is an option that our model optimize initial mesh. It was used when initial mesh is not perfect. In that case model can change vertices positions, and of course Gaussians positions, but it won't change number of faces, or neither number of Gaussians.

Which option can prevent the initial mesh from being optimized?
