### ISSUE TITLE
How can i get transforms_train.json from my data

### ISSUE THREAD

**Issue by yungommi** [waczjoan/gaussian-mesh-splatting#14]
i have 250 photos and colmap(sparse or dense) output.
how can i get transform_train.json from mine?

**Comment by piotr310100** [comment]
Hi,
you should be able to obtain it by using for example this script from instant-ngp repository https://github.com/NVlabs/instant-ngp/blob/master/scripts/colmap2nerf.py. However if you have just photos and no mesh you should most likely run the code with the gs_flat/gs_points flag instead of gs_mesh.

**Comment by ManOfStory** [comment]
Hello, I run the colmap2nerf.py as your mentioned above with hotdog's images. However, The result is "no convergence", the error code I list below, how can I generate the transforms_train.json with the hogdog's images? Thank you!
`I0620 22:35:11.469830 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.472297 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.472959 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.475425 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.476089 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.478544 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.479228 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.481621 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.482295 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.484755 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.485415 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.487890 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.488565 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.491008 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.491672 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.494063 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.494745 11476 incremental_mapper.cc:265] Finding good initial image pair
I0620 22:35:11.497138 11476 incremental_mapper.cc:269] => No good initial image pair found.
I0620 22:35:11.497220 11476 timer.cc:91] Elapsed time: 0.666 [minutes]
==== running: colmap bundle_adjuster --input_path colmap_sparse/0 --output_path colmap_sparse/0 --BundleAdjustment.refine_principal_point 1
I0620 22:35:11.540465 13472 misc.cc:198]
==============================================================================
Global bundle adjustment
==============================================================================
I0620 22:35:11.973769 13472 bundle_adjustment.cc:866]
Bundle adjustment report:
    Residuals : 4968
   Parameters : 3058
   Iterations : 45
         Time : 0.430327 [s]
 Initial cost : 0.23405 [px]
   Final cost : 0.23319 [px]
  Termination : Convergence

I0620 22:35:11.973799 13472 timer.cc:91] Elapsed time: 0.007 [minutes]
==== running: mkdir colmap_text
==== running: colmap model_converter --input_path colmap_sparse/0 --output_path colmap_text --output_type TXT
outputting to transforms.json...
camera 1:
        res=(800.0, 800.0)
        center=(411.8908334149666, 371.52371570672915)
        focal=(1346.186917631821, 1423.572476985837)
        fov=(33.09711307373078, 31.388945489320005)
        k=(0.4526649231735813, -14.888869859638497) p=(-0.05545366318381546, 0.03252210165494483)
./hotdog_train/r_20.png sharpness= 349.563809375
./hotdog_train/r_12.png sharpness= 310.815190625
./hotdog_train/r_18.png sharpness= 319.477234375
up vector was [-0.98776828 -0.02606481 -0.15373498]
computing center of attention...
[-25.85897426  -3.3130837   -0.13101653]
avg camera distance from origin 26.48482140722281
3 frames
writing transforms.json
`

**Comment by waczjoan** [comment]
Hi, 
To help you more precisely, let me ask few questions: 

- did you run code with  flag ---gs_type gs_flat and than run render with  --gs_type gs_flat/gs_points?

- why/for what do you need transformation_dataset.json file? 

Tansformation_dataset.json is file dedicated mostly for blender type dataset, there is possible use mentioned script colmap2nerf to create this file, but it is not necessary in our method (you should train flat GS and then parameterized gaussians using gs_points). 
But for more information about transformation.jskn please take a look also here:  
- https://github.com/NVlabs/instant-ngp/issues/61
- https://docs.nerf.studio/quickstart/data_conventions.html

For hotdog we had already this tranfsformation.json from benchmark open dataset: https://drive.google.com/drive/folders/1JDdLGDruGNXWnM1eqY1FNL9PlStjaKWi
