### ISSUE TITLE
The original formulas and code formulas about scale and rotation are different

### ISSUE THREAD

**Issue by liuyu19970607** [waczjoan/gaussian-mesh-splatting#15]
First and most important, thank you for your generosity in making your code open source. However, we found that the formula for calculating r1 r2 s1 and s2 in the original text is different from the formula in the code. For example, in the original text r_{2} = norm(v1-m), but in the code r_{2} = norm(v2-m). I would like to ask, will this have any impact on the implementation effect?

**Comment by hfreecmu** [comment]
I am also curious, what is the reason for the formulas being different? Should the one in the code be used or the one from the paper?

**Comment by piotr310100** [comment]
The choice of the vertices is arbitrary as long as the choice is used throughout the entire training, which means that both versions should give similiar results. The difference between formulas in the code and paper is an oversight on our part.

I've ran the training using both verisons using the following command on a hotdog dataset: 
`
python train.py --eval -s <data_path> -m <output_path> --gs_type gs_mesh -w
`

Here are the results for both versions for comparison:

Code
  SSIM :    0.9686840
  PSNR :   34.5407867
  LPIPS:    0.0485639

Paper
  SSIM :    0.9687092
  PSNR :   34.5666122
  LPIPS:    0.0482040
