### ISSUE TITLE
Extract Mesh 

### ISSUE THREAD

**Issue by aiyb1314** [waczjoan/gaussian-mesh-splatting#2]
How to get the generated and optimized mesh model？

**Comment by waczjoan** [comment]
Hi, 
Please find "Tutorial" section in README, We put there step by step instruction, based on `hotdog` dataset. If you have any trouble, I will be happy to help. Also, if there is something written that is not clear - please let me know -- I will be happy to fill in the missing information for other users as well.

**Comment by homee-dennis** [comment]
@waczjoan Hi,
First of all, thanks for the good work and really appreciate make it open source. 

I'm wondering what exactly your gs_mesh output is ? Can we get a mesh file like .obj ? Or the result is till 3DGS pointcloud (.ply) but with mesh face constrain making 3DGS more "structure" ?

**Comment by waczjoan** [comment]
@homee-dennis  thank you!

The output closely resembles what 3DGS generates, with the possibility of returning extra data depending on the chosen model. For instance, it may include enumerated vertices/pseudomesh, or in the case of gs_flame, it provides vectors enabling the utilization of the FLAME model. I recommend delving into the project and paying attention to the `additional_attrs` within the "save_ply" method in specific model.

There have been inquiries about whether the model yields an `.obj` file. Currently, it does not, as parameters like vertices and faces suffice for our purposes. However, I am considering sharing a script that converts these values into an `.obj` file for those who are interested :)
