### ISSUE TITLE
where are blend files？

### ISSUE THREAD

**Issue by Simon-kjx** [waczjoan/gaussian-mesh-splatting#20]
I opened the link you provided, but there are no blend files in it?

**Comment by waczjoan** [comment]
Hi, We linked to official NeRF dataset (https://www.matthewtancik.com/nerf)

Link is not available right now. Please check:
https://github.com/bmild/nerf/issues/211

**Comment by nirmalsnair** [comment]
Hi @waczjoan , it looks like the [link to the blend files](https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1) in the [tutorial](https://github.com/waczjoan/gaussian-mesh-splatting?tab=readme-ov-file#train) is currently broken. Could you please check? Thanks!

**Comment by frozzzen3** [comment]
Try this, https://drive.google.com/file/d/1NQu8ULQJzcilaiAR8WrNXmvg-lReABjI/view?usp=sharing
