### ISSUE TITLE
Is there a way to convert a pseudo mesh into a mesh?

### ISSUE THREAD

**Issue by wheltz** [waczjoan/gaussian-mesh-splatting#3]
Thank you for your work! The pseudo mesh I saw in the paper seemed to be disconnected from each other. I want to know if it is possible to build a mesh through GaMeS without a mesh

**Comment by waczjoan** [comment]
Thank you!

To be more specific, a pseudomesh comprises unconnected entities known as pseudofaces. The term "pseudo" reflects the deviation from the typical mesh assumptions, notably the lack of vertex connectivity, as you rightly pointed out.

Allow me to rephrase the question — can a mesh be derived from a pseudomesh? This poses an intriguing challenge. While we've explored numerous potential solutions, we're not yet ready to discuss them publicly. However, if you're interested in collaborating, we welcome you to reach out to us (contact details are provided in the article).

In the meantime, I recommend investigating the SUGAR project mentioned in paper, as they specialize in mesh creation.
