### ISSUE TITLE
some errors in the environment configuration part

### ISSUE THREAD

**Issue by FVL2020** [waczjoan/gaussian-mesh-splatting#32]
You wrote "conda activate gaussian_splatting_mesh" as "conda gaussian_splatting_mesh" in the environment configuration tutorial.
![屏幕截图 2024-12-28 162217](https://github.com/user-attachments/assets/d6063b33-ef3f-41bc-8b2b-fb26af5ce9c2)

**Comment by waczjoan** [comment]
thanks! I updated README
