### ISSUE TITLE
no rendering colors in SIBR with gs_flat models

### ISSUE THREAD

**Issue by cv-lab-x** [waczjoan/gaussian-mesh-splatting#5]
thanks for your great work,some little errors : there're no rendering colors with gs_flat models in SIBR?
Looking forward to your reply, thanks! @waczjoan

**Comment by waczjoan** [comment]
Thank you!

May I ask additional context regarding the issue? Perhaps a code snippet or a comparison with another model could help elucidate the problem further.

I'd like to stress at this moment that `flat Gaussian splatting` essentially yields identical results to original `Gaussian splatting`, except that it enforces flatness during the learning phase. Additionally, it employs the same pruning processes. Consequently, post-training with flat Gaussian splatting, we obtain comprehensive information about the Gaussians, including their position, scale, rotation, `color`, opacity, and so forth. But I have a feeling that's not what you're asking about.
