### ISSUE TITLE
Is it possible to use a simple shape mesh (such as a sphere) as the initial mesh for modeling?

### ISSUE THREAD

**Issue by zhirui-gao** [waczjoan/gaussian-mesh-splatting#8]
Thanks for your great work!
I wonder is it possible to use a simple shape mesh (such as a sphere) as the initial mesh for modeling? I'm interested in whether a mesh-based 3DGS can start from a randomly initialized mesh and learn more refined mesh details by learning the displacement of each vertex, (similar to the FLAME model you provide). In this way, we can get a connected mesh instead of disconnected  faces. 
I'm contemplating whether starting from a template mesh holds significance compared to initializing from the discrete points of an original 3DGS.

**Comment by waczjoan** [comment]
Hi, I'm really sorry for late response! I read your issued and than forgot answer 😅 

First of all, I think your question is really interesting, we also discussed possibilities to use a simple shape mesh. In perfect situation that could be possible, but... I think it is too difficult for the model, and some "mesh rules" should be implemented.  Now you don't have any control for creating mesh processes, but for example rule: "mesh has to be convex" should be applied. 


So.... If you have easy shape, I believe if you take "init mesh" with similar scale to object it should works. But in practice I know the best solution is used as similar mesh it is possible. There are a lot of methods which try to create mesh, so maybe using them should be first step?

**Comment by zhirui-gao** [comment]
I see. Thanks for your reply!
