### ISSUE TITLE
How can I use my data set to get "rotation" in Transforms_train.json?

### ISSUE THREAD

**Issue by kikiwxalynika** [waczjoan/gaussian-mesh-splatting#9]
Hi, I want to complete the process using my own data set. But the transforms.json we get from colmap does not contain the rotation parameter in hotdog's transforms_train.json. How can I get rotation? Thanks!

**Comment by piotr310100** [comment]
Hi, the rotation parameter in transforms_train.json is not used by us in nerf synthetic (e.g. hotdog) datasets. If in transforms.json you have a transformation matrix you should be able to run the code on your dataset. The rotation parameter used in CameraInfo can be then obtained from this matrix as shown here https://github.com/waczjoan/gaussian-mesh-splatting/blob/7a16646828e9d43bb738ef92ba498838c755db66/scene/dataset_readers.py#L197
